### ISSUE TITLE
alg implemention

### ISSUE THREAD

**Issue by kruskr** [kazizzad/BDQN-MxNet-Gluon#1]
why there is a decomposition when thompson sampling happens,does it necessary

**Comment by kazizzad** [comment]
Could you please be more specific? maybe line number, topic, part of the pseudo algorithm, or a concept.

**Comment by kruskr** [comment]
Yeah,when i read your source code,i found that,"np.linalg.cholesky(((Cov_W[i]+nd.transpose(Cov_W[i]))/2."

**Comment by kazizzad** [comment]
You use the result of this decomposing to map a Gaussian normal random vector to a Gaussian random vector with the desired covariance matrix. 

Please let me know if you think more explanation is required. I would be happy to provide.

**Comment by kruskr** [comment]
Thanks,i got it !
